spring:
  config:
    import:
      - file:./private/secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: api-platform
  profiles:
    active: dev
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    username: liruohrh@163.com
    password: UXQVXVFYYFSNMCOH
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
#        - "file:../platform-frontend/dist"
server:
  port: 9000
  servlet:
    context-path: /api-platform
    session:
      cookie:
        path: /
        same-site: none
        secure: true
api-gateway:
  replay-attack:
    max-alive-time: 300000
api-platform:
  login:
    white-list:
      - /static/**
      - /pages/**
      - /index.html
      - /api/**
      - /doc.html
      - /webjars/**
      - /favicon.ico
      - /swagger-ui.html
      - /v3/api-docs/**
      - /email/captcha
      - /oss/file
      - /auth/login
      - /auth/register
      - /auth/passwd
      - /oss/static/**
      - /http-api/search
      - GET,/http-api/*
      - GET,/comment
      - GET,/comment/reply
