spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_platform_test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
logging:
  level:
    io.github.liruohrh.apiplatform.exception: warn
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl